### PR TITLE
Replaced deprecated Fixnum (since Ruby 2.4) with Integer

### PR DESCRIPTION
**Pull request by derikz**
see  [http://blog.bigbinary.com/2016/11/18/ruby-2-4-unifies-fixnum-and-bignum-into-integer.html ](http://blog.bigbinary.com/2016/11/18/ruby-2-4-unifies-fixnum-and-bignum-into-integer.html )

-Derik.

### CODE REVIEW

**Comment by mindware** [comment]
@junegunn need anything for this to get merged?

**Comment by junegunn** [comment]
Merged, thanks. I don't use this gem anymore, but I'll release a new version shortly.

**Comment by junegunn** [comment]
0.1.3 is up.

**Comment by derikz** [comment]
Great, thanks. I delete my fork then.
-Derik.

**Comment by mindware** [comment]
Great. I think this can be closed now.

**Pull request merged**
